; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Fri Dec 09 2022 14:47:45 GMT+0100 (Mitteleuropäische Normalzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


